# Generated by Django 5.0.2 on 2024-02-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passissued',
            options={'verbose_name': 'Pass Issued', 'verbose_name_plural': 'Passes Issued'},
        ),
        migrations.AlterModelOptions(
            name='passrequested',
            options={'verbose_name': 'Pass Requested', 'verbose_name_plural': 'Passes Requested'},
        ),
        migrations.AddField(
            model_name='passissued',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='passrequested',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
